name: Build and Deploy FAST Documentation
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Build docs
        run: |
          mkdir build
          cd build
          mkdir documentation
          cd documentation
          echo "<h1>Under construction</h1>" > index.html
          echo "<h1>Test</h1>" > test.html
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/documentation/
          retention-days: 1
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

